USE [HCAD]
GO


CREATE TABLE [dbo].[real_acct](
	[ACCOUNT] [nvarchar](50) NOT NULL,
	[TAX_YEAR] [nvarchar](4) NULL,
	[MAILTO] [nvarchar](100) NULL,
	[MAIL_ADDR_1] [nvarchar](50) NULL,
	[MAIL_ADDR_2] [nvarchar](50) NULL,
	[MAIL_CITY] [nvarchar](50) NULL,
	[MAIL_STATE] [nchar](2) NULL,
	[MAIL_ZIP] [nvarchar](10) NULL,
	[MAIL_COUNTRY] [nvarchar](50) NULL,
	[UNDELIVERABLE] [nvarchar](1) NULL,
	[STR_PFX] [nchar](2) NULL,
	[STR_NUM] [int] NULL,
	[STR_NUM_SFX] [nchar](3) NULL,
	[STR_NAME] [nvarchar](50) NULL,
	[STR_SFX] [nvarchar](25) NULL,
	[STR_SFX_DIR] [nchar](2) NULL,
	[STR_UNIT] [nvarchar](15) NULL,
	[SITE_ADDR_1] [nvarchar](50) NULL,
	[SITE_ADDR_2] [nvarchar](50) NULL,
	[SITE_ADDR_3] [nvarchar](10) NULL,
	[STATE_CLASS] [nvarchar](16) NULL,
	[SCHOOL_DIST] [nvarchar](5) NULL,
	[MAP_FACET] [nvarchar](6) NULL,
	[KEY_MAP] [nvarchar](6) NULL,
	[NEIGHBORHOOD_CODE] [nvarchar](11) NULL,
	[NEIGHBORHOOD_GROUP] [nvarchar](8) NULL,
	[MARKET_AREA_1] [nvarchar](8) NULL,
	[MARKET_AREA_1_DSCR] [nvarchar](50) NULL,
	[MARKET_AREA_2] [nvarchar](8) NULL,
	[MARKET_AREA_2_DSCR] [nvarchar](50) NULL,
	[ECON_AREA] [nvarchar](5) NULL,
	[ECON_BLD_CLASS] [nvarchar](5) NULL,
	[CENTER_CODE] [nvarchar](5) NULL,
	[YR_IMPR] [nvarchar](4) NULL,
	[YR_ANNEXED] [nvarchar](4) NULL,
	[SPLT_DT] [nchar](20) NULL,
	[DSC_CD] [nchar](2) NULL,
	[NXT_BUILDING] [nvarchar](10) NULL,
	[TOTAL_BUILDING_AREA] [nvarchar](12) NULL,
	[TOTAL_LAND_AREA] [nvarchar](12) NULL,
	[ACREAGE] [nvarchar](13) NULL,
	[CAP_ACCOUNT] [nvarchar](7) NULL,
	[SHARED_CAD_CODE] [nchar](3) NULL,
	[LAND_VALUE] [nvarchar](12) NULL,
	[IMPROVEMENT_VALUE] [nvarchar](12) NULL,
	[EXTRA_FEATURES_VALUE] [nvarchar](12) NULL,
	[AG_VALUE] [nvarchar](12) NULL,
	[ASSESSED_VALUE] [nvarchar](12) NULL,
	[TOTAL_APPRAISED_VALUE] [nvarchar](12) NULL,
	[TOTAL_MARKET_VALUE] [nvarchar](12) NULL,
	[PRIOR_LND_VALUE] [nvarchar](12) NULL,
	[PRIOR_IMPR_VALUE] [nvarchar](12) NULL,
	[PRIOR_X_FEATURES_VALUE] [nvarchar](12) NULL,
	[PRIOR_AG_VALUE] [nvarchar](12) NULL,
	[PRIOR_TOTAL_APPRAISED_VALUE] [nvarchar](12) NULL,
	[PRIOR_TOTAL_MARKET_VALUE] [nvarchar](12) NULL,
	[NEW_CONSTRUCTION_VALUE] [nvarchar](12) NULL,
	[TOTAL_RCN_VALUE] [nvarchar](12) NULL,
	[VALUE_STATUS] [nvarchar](36) NULL,
	[NOTICED] [nvarchar](1) NULL,
	[NOTICE_DATE] [nvarchar](25) NULL,
	[PROTESTED] [nvarchar](1) NULL,
	[CERTIFIED_DATE] [nvarchar](25) NULL,
	[LAST_INSPECTED_DATE] [nvarchar](25) NULL,
	[LAST_INSPECTED_BY] [nchar](5) NULL,
	[NEW_OWNER_DATE] [nvarchar](25) NULL,
	[LEGAL_DSCR_1] [nvarchar](50) NULL,
	[LEGAL_DSCR_2] [nvarchar](50) NULL,
	[LEGAL_DSCR_3] [nvarchar](50) NULL,
	[LEGAL_DSCR_4] [nvarchar](50) NULL,
	[JURS] [nvarchar](100) NULL
 ) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_real_acct] ON [dbo].[real_acct]
(
	[ACCOUNT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]



CREATE TABLE [dbo].[real_neighborhood_code](
	[NEIGHBORHOOD_CD] [nvarchar](11) NOT NULL,
	[GROUP_CD] [nvarchar](12) NULL,
	[DESCRIPTION] [nvarchar](50) NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_real_neighborhood_code] ON [dbo].[real_neighborhood_code]
(
	[NEIGHBORHOOD_CD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


CREATE TABLE [owners] (
	[ACCOUNT] NVARCHAR(13) NOT NULL,
	[LINE_NUMBER] INTEGER NOT NULL,
	[NAME] NVARCHAR(100),
	[AKA] NVARCHAR(50),
	[PCT_OWN] NVARCHAR(5))
	on [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_owners] ON [dbo].[owners]
(
	[ACCOUNT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO



CREATE TABLE [building_other] (
	[ACCOUNT] NVARCHAR(50),
	[USE_CODE] NVARCHAR(16),
	[BLD_NUM] INTEGER NOT NULL,
	[IMPROV_TYPE] NCHAR(4),
	[BUILDING_STYLE_CODE] NCHAR(4),
	[CLASS_STRUCTURE] NCHAR(3),
	[CLASS_STRUC_DESCRIPTION] NVARCHAR(50),
	[NOTICED_DEPR_VALUE] NVARCHAR(12),
	[DEPRECIATION_VALUE] NVARCHAR(12),
	[MS_REPLACEMENT_COST] NVARCHAR(12),
	[CAMA_REPLACEMENT_COST] NVARCHAR(12),
	[ACCRUED_DEPR_PCT] NVARCHAR(8),
	[QUALITY] NCHAR(2),
	[QUALITY_DESCRIPTION] NVARCHAR(50),
	[DATE_ERECTED] NVARCHAR(4),
	[EFFECTIVE_DATE] NVARCHAR(4),
	[YR_REMODEL] NCHAR(4),
	[YR_ROLL] NCHAR(4),
	[APPRAISED_BY] NCHAR(5),
	[APPRAISED_DATE] NVARCHAR(10),
	[NOTE] NVARCHAR(150),
	[IMPR_SQ_FT] NVARCHAR(12),
	[ACTUAL_AREA] NVARCHAR(12),
	[HEAT_AREA] NVARCHAR(12),
	[GROSS_AREA] NVARCHAR(12),
	[EFFECTIVE_AREA] NVARCHAR(12),
	[BASE_AREA] NVARCHAR(12),
	[PERIMETER] NVARCHAR(12),
	[PERCENT_COMPLETE] NVARCHAR(4),
	[CATEGORY] NCHAR(2),
	[CATEGORY_DSCR] NVARCHAR(50),
	[PROPERTY_NAME] NVARCHAR(50),
	[UNITS] NVARCHAR(15),
	[NET_RENT_AREA] NVARCHAR(10),
	[LEASE_RATE] NVARCHAR(10),
	[OCCUPANCY_RATE] NVARCHAR(10),
	[TOTAL_INCOME] NVARCHAR(10)
)
go
CREATE NONCLUSTERED INDEX [IX_building_other] ON [dbo].[building_other]
(
	[ACCOUNT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO




CREATE TABLE [jur_tax_dist_exempt_value] (
	[RP_TYPE] NVARCHAR(4) NOT NULL,
	[TAX_DIST] NVARCHAR(6),
	[TAX_DISTRICT_NAME] NVARCHAR(100),
	[PRIOR_YR_RATE] NVARCHAR(10),
	[CURRENT_YR_RATE] NVARCHAR(10),
	[ABT] INTEGER,
	[APD] INTEGER,
	[APO] INTEGER,
	[APR] INTEGER,
	[APS] INTEGER DEFAULT 0,
	[DIS] INTEGER,
	[HIS] INTEGER,
	[LIH] INTEGER DEFAULT 0,
	[MCL] INTEGER,
	[OVR] INTEGER,
	[PAR] INTEGER,
	[PDS] INTEGER,
	[PEX] INTEGER,
	[POL] INTEGER,
	[POV] INTEGER,
	[PRO] INTEGER,
	[RES] INTEGER,
	[SFT] INTEGER DEFAULT 0,
	[SOL] INTEGER,
	[SSA] INTEGER,
	[SSD] INTEGER,
	[SSF] INTEGER DEFAULT 0,
	[STT] INTEGER,
	[STX] INTEGER,
	[SUR] INTEGER,
	[TOT] INTEGER,
	[V11] INTEGER,
	[V12] INTEGER,
	[V13] INTEGER,
	[V14] INTEGER,
	[V21] INTEGER,
	[V22] INTEGER,
	[V23] INTEGER,
	[V24] INTEGER,
	[VCH] INTEGER,
	[VS1] INTEGER,
	[VS2] INTEGER,
	[VS3] INTEGER,
	[VS4] INTEGER,
	[VTX] INTEGER
)
CREATE NONCLUSTERED INDEX [IX_jur_tax_dist_exempt_value] ON [dbo].[jur_tax_dist_exempt_value]
(
	[TAX_DIST] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


CREATE TABLE [jur_value] (
	[ACCOUNT] NVARCHAR(13) NOT NULL,
	[TAX_DISTRICT] NVARCHAR(6) NOT NULL,
	[TYPE] NCHAR(1),
	[PCT_DISTRICT] NVARCHAR(6),
	[APPRAISED_VALUE] NVARCHAR(13),
	[TAXABLE_VALUE] NVARCHAR(13),
	CONSTRAINT [jur_value$ACCOUNT] PRIMARY KEY ([ACCOUNT], [TAX_DISTRICT])
)



--this data is part of a combined text file, code_desc_real.txt.  state class section
create table reusecodes 
(Code nvarchar(20),Code2 nvarchar(10),Description nvarchar(170))
