select 'arb_hearings_pp' as tablename, count(*) as countofrows from arb_hearings_pp
 union select 'arb_hearings_real' as tablename, count(*) as countofrows from arb_hearings_real
 union select 'arb_protest_pp' as tablename, count(*) as countofrows from arb_protest_pp
 union select 'arb_protest_real' as tablename, count(*) as countofrows from arb_protest_real
 union select 'building_other' as tablename, count(*) as countofrows from building_other
 union select 'building_res' as tablename, count(*) as countofrows from building_res
 union select 'deeds' as tablename, count(*) as countofrows from deeds
 union select 'exterior' as tablename, count(*) as countofrows from exterior
 union select 'extra_features' as tablename, count(*) as countofrows from extra_features
 union select 'extra_features_detail1' as tablename, count(*) as countofrows from extra_features_detail1
 union select 'extra_features_detail2' as tablename, count(*) as countofrows from extra_features_detail2
 union select 'fixtures' as tablename, count(*) as countofrows from fixtures
 union select 'jur_exempt' as tablename, count(*) as countofrows from jur_exempt
 union select 'jur_exempt_cd' as tablename, count(*) as countofrows from jur_exempt_cd
 union select 'jur_exemption_dscr' as tablename, count(*) as countofrows from jur_exemption_dscr
 union select 'jur_tax_dist_exempt_value' as tablename, count(*) as countofrows from jur_tax_dist_exempt_value
 union select 'jur_tax_dist_percent_rate' as tablename, count(*) as countofrows from jur_tax_dist_percent_rate
 union select 'jur_value' as tablename, count(*) as countofrows from jur_value
 union select 'land' as tablename, count(*) as countofrows from land
 union select 'land_ag' as tablename, count(*) as countofrows from land_ag
 union select 'owners' as tablename, count(*) as countofrows from owners
 union select 'ownership_history' as tablename, count(*) as countofrows from ownership_history
 union select 'parcel_tieback' as tablename, count(*) as countofrows from parcel_tieback
 union select 'permits' as tablename, count(*) as countofrows from permits
 union select 'real_acct' as tablename, count(*) as countofrows from real_acct
 union select 'real_neighborhood_code' as tablename, count(*) as countofrows from real_neighborhood_code
 union select 'structural_elem1' as tablename, count(*) as countofrows from structural_elem1
 union select 'structural_elem2' as tablename, count(*) as countofrows from structural_elem2
 union select 't_business_acct' as tablename, count(*) as countofrows from t_business_acct
 union select 't_business_detail' as tablename, count(*) as countofrows from t_business_detail
 union select 't_jur_exempt' as tablename, count(*) as countofrows from t_jur_exempt
 union select 't_jur_tax_dist_exempt_value' as tablename, count(*) as countofrows from t_jur_tax_dist_exempt_value
 union select 't_jur_tax_dist_percent_rate' as tablename, count(*) as countofrows from t_jur_tax_dist_percent_rate
 union select 't_jur_value' as tablename, count(*) as countofrows from t_jur_value
 union select 't_pp_c' as tablename, count(*) as countofrows from t_pp_c
 union select 't_pp_e' as tablename, count(*) as countofrows from t_pp_e
 UNION select 't_pp_l' as tablename, count(*) as countofrows from t_pp_l;
